[package]
name = "cowsay"
version = "0.1.0"
authors = ["Prabir Shrestha <mail@prabir.me>"]
edition = "2018"
license = "MIT"
description = "cowsay"
repository = "https://github.com/prabirshrestha/cowsay.rs"

[dependencies]
structopt = "0.3.21"
