name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - ci
    tags:
      - 'v*.*.*'

jobs:
  style:
    name: check style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt, clippy
    - name: rust fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: clippypush
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

  build:
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    needs: [style]
    strategy:
      matrix:
        build: [linux, linux-arm, macos, winmsvc]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            usecross: false
          - build: linux-arm
            os: ubuntu-latest
            rust: stable
            target: arm-unknown-linux-musleabihf
            usecross: true
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            usecross: false
          - build: winmsvc
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            usecross: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        profile: minimal
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.usecross }}
        command: build
        args: --verbose --locked --all --release --target ${{ matrix.target }}

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.usecross }}
        command: test
        args: --verbose --locked --all --release --target ${{ matrix.target }}
